/**
 * Backend deployment-package extraction — PowerShell script generator.
 *
 * Implements the behaviour described in the task spec, section 4:
 *
 *   - For every *.zip under $deploymentBasePath:
 *       - Extract to a sibling folder named after the zip (BaseName)
 *       - Overwrite existing extraction if necessary
 *       - Delete the zip after successful extraction
 *       - Find web.config and rewrite:
 *           stdoutLogEnabled="false"  →  stdoutLogEnabled="true"
 *           hostingModel="inprocess"  →  hostingModel="OutOfProcess"
 *       - Leave other settings alone
 *   - Log every operation with [Setup] prefix
 *   - Report missing web.config clearly
 *
 * Pure data → string transformation. The script itself is generated and
 * downloaded by the UI (existing Setup Agent pattern).
 *
 * Implementation note: string concatenation (not template literals) so the
 * embedded PowerShell `$var` and `${expr}` syntax doesn't collide with
 * JavaScript template substitution.
 */

export interface ExtractionScriptOptions {
  /** Where the script writes its log lines. */
  logPath?: string
}

export function buildExtractionScript(
  deploymentBasePath: string,
  opts: ExtractionScriptOptions = {},
): string {
  const base = escapePs(deploymentBasePath)
  const scriptLog = escapePs(
    opts.logPath ?? "C:\\Raawee\\Logs\\setup-agent-extract.log",
  )

  const lines: string[] = []
  lines.push("# =====================================================================")
  lines.push("# Backend deployment extraction — generated by Setup Agent.")
  lines.push("# Idempotent: zip files that have already been extracted & deleted are")
  lines.push("# simply absent and the loop becomes a no-op.")
  lines.push("# =====================================================================")
  lines.push("")
  lines.push("$ErrorActionPreference = 'Continue'")
  lines.push("$ProgressPreference = 'SilentlyContinue'")
  lines.push("")
  lines.push('$Path = "' + base + '"')
  lines.push('$ScriptLog = "' + scriptLog + '"')
  lines.push("")
  lines.push("New-Item -Path (Split-Path -Parent $ScriptLog) -ItemType Directory -Force | Out-Null")
  lines.push("")
  lines.push("function Write-SetupLog {")
  lines.push("    param([string]$Message, [string]$Level = \"INFO\")")
  lines.push("    $line = \"[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message\"")
  lines.push("    Add-Content -Path $ScriptLog -Value $line")
  lines.push('    if ($Level -eq "ERROR") { Write-Host $line -ForegroundColor Red }')
  lines.push('    elseif ($Level -eq "WARN") { Write-Host $line -ForegroundColor Yellow }')
  lines.push('    else { Write-Host $line -ForegroundColor Cyan }')
  lines.push("}")
  lines.push("")
  lines.push("if (-not (Test-Path $Path)) {")
  lines.push('    Write-SetupLog "Deployment path not found: $Path" "ERROR"')
  lines.push("    exit 1")
  lines.push("}")
  lines.push("")
  lines.push('Write-SetupLog "Extracting backend packages from: $Path"')
  lines.push("Get-ChildItem -Path $Path -Filter \"*.zip\" | ForEach-Object {")
  lines.push("    $destFolder = Join-Path $Path $_.BaseName")
  lines.push("    try {")
  lines.push('        Write-SetupLog "Extracting: $($_.Name) -> $($_.BaseName)\\"')
  lines.push("        Expand-Archive -Path $_.FullName -DestinationPath $destFolder -Force")
  lines.push('        Write-SetupLog "Extracted: $($_.BaseName)"')
  lines.push("")
  lines.push("        Remove-Item -Path $_.FullName -Force")
  lines.push('        Write-SetupLog "Deleted zip: $($_.Name)"')
  lines.push("")
  lines.push("        $webConfig = Join-Path $destFolder \"web.config\"")
  lines.push("        if (Test-Path $webConfig) {")
  lines.push("            $content = Get-Content $webConfig -Raw")
  lines.push("            $originalContent = $content")
  lines.push("")
  lines.push("            if ($content -match 'stdoutLogEnabled=\"false\"') {")
  lines.push("                $content = $content -replace 'stdoutLogEnabled=\"false\"', 'stdoutLogEnabled=\"true\"'")
  lines.push("            }")
  lines.push("            if ($content -match 'hostingModel=\"inprocess\"') {")
  lines.push("                $content = $content -replace 'hostingModel=\"inprocess\"', 'hostingModel=\"OutOfProcess\"'")
  lines.push("            }")
  lines.push("")
  lines.push("            if ($content -ne $originalContent) {")
  lines.push("                Set-Content $webConfig $content -Encoding UTF8")
  lines.push('                Write-SetupLog "web.config updated: $($_.BaseName)"')
  lines.push("            } else {")
  lines.push('                Write-SetupLog "web.config already correct: $($_.BaseName)"')
  lines.push("            }")
  lines.push("        } else {")
  lines.push('            Write-SetupLog "web.config NOT FOUND in: $($_.BaseName)" "WARN"')
  lines.push("        }")
  lines.push("    } catch {")
  lines.push('        Write-SetupLog "Failed to process $($_.Name): $($_.Exception.Message)" "ERROR"')
  lines.push("    }")
  lines.push("}")
  lines.push("")
  lines.push('Write-SetupLog "All done! ZIPs extracted, deleted, and web.configs updated."')

  return lines.join("\n") + "\n"
}

/** Escape a string for embedding inside a double-quoted PowerShell string. */
function escapePs(input: string): string {
  return input.replace(/`/g, "``").replace(/"/g, '`"').replace(/\$/g, "`$")
}
