/**
 * MongoDB replica-set / configuration module.
 *
 * Generates an idempotent PowerShell script that:
 *   1. Inspects the existing MongoDB installation
 *   2. Idempotently writes the `replication.replSetName` block into the
 *      mongod.cfg (only when missing or mismatched)
 *   3. Restarts the MongoDB Windows service
 *   4. Initializes the replica set ONLY if `rs.status()` reports no init
 *   5. Reports the final replica-set state
 *
 * The orchestrator invokes this module to *generate* the script that an
 * administrator runs on the target server (the existing Setup Agent
 * pattern — Next.js cannot directly invoke PowerShell on a remote
 * Windows server). The script does NOT include the PAT or any other
 * Azure DevOps secret, but it does need the `mongoDb` config block.
 *
 * Implementation note: string concatenation (not template literals) so the
 * embedded PowerShell `$var` and `${expr}` syntax doesn't collide with
 * JavaScript template substitution.
 */

import type { MongoDbConfig } from "./types"

export interface MongoSetupScriptOptions {
  /** Path the script writes its log lines to. */
  logPath?: string
}

/**
 * Build the MongoDB setup script. The result is a single, self-contained
 * PowerShell string. The script must be run as Administrator — it
 * touches the Windows service control manager and the mongod config file
 * (which lives under `C:\Program Files\…`).
 */
export function buildMongoSetupScript(
  config: MongoDbConfig,
  opts: MongoSetupScriptOptions = {},
): string {
  const replicaSetName = escapePowerShell(config.replicaSetName)
  const bindIp = escapePowerShell(config.bindIp)
  const port = Number.isFinite(config.port) ? config.port : 27017
  const configFilePath = escapePowerShell(config.configFilePath)
  const dbPath = escapePowerShell(config.dbPath)
  const logPath = escapePowerShell(config.logPath)
  const serviceName = escapePowerShell(config.serviceName)
  const scriptLog = escapePowerShell(
    opts.logPath ?? "C:\\Raawee\\Logs\\setup-agent-mongo.log",
  )

  const lines: string[] = []
  lines.push("# =====================================================================")
  lines.push("# MongoDB installation & replica-set configuration")
  lines.push("# Generated by Setup Agent. Idempotent — safe to re-run.")
  lines.push("# Run as Administrator.")
  lines.push("# =====================================================================")
  lines.push("")
  lines.push("$ErrorActionPreference = 'Stop'")
  lines.push("$ProgressPreference = 'SilentlyContinue'")
  lines.push("")
  lines.push('$ScriptLog = "' + scriptLog + '"')
  lines.push('$ServiceName = "' + serviceName + '"')
  lines.push('$ConfigFile = "' + configFilePath + '"')
  lines.push('$DbPath = "' + dbPath + '"')
  lines.push('$LogPath = "' + logPath + '"')
  lines.push('$BindIp = "' + bindIp + '"')
  lines.push("$Port = " + port)
  lines.push('$ReplicaSetName = "' + replicaSetName + '"')
  lines.push("")
  lines.push("New-Item -Path (Split-Path -Parent $ScriptLog) -ItemType Directory -Force | Out-Null")
  lines.push("")
  lines.push("function Write-SetupLog {")
  lines.push("    param([string]$Message, [string]$Level = \"INFO\")")
  lines.push("    $line = \"[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message\"")
  lines.push("    Add-Content -Path $ScriptLog -Value $line")
  lines.push('    if ($Level -eq "ERROR") { Write-Host $line -ForegroundColor Red }')
  lines.push('    elseif ($Level -eq "WARN") { Write-Host $line -ForegroundColor Yellow }')
  lines.push('    else { Write-Host $line -ForegroundColor Cyan }')
  lines.push("}")
  lines.push("")
  lines.push('Write-SetupLog "Starting MongoDB setup (replica set: $ReplicaSetName)."')
  lines.push("")
  lines.push("# --- Step 1: ensure data & log directories exist -------------------------")
  lines.push("if (-not (Test-Path $DbPath)) {")
  lines.push("    New-Item -Path $DbPath -ItemType Directory -Force | Out-Null")
  lines.push('    Write-SetupLog "Created MongoDB data directory: $DbPath"')
  lines.push("}")
  lines.push("$logDir = Split-Path -Parent $LogPath")
  lines.push("if ($logDir -and -not (Test-Path $logDir)) {")
  lines.push("    New-Item -Path $logDir -ItemType Directory -Force | Out-Null")
  lines.push('    Write-SetupLog "Created MongoDB log directory: $logDir"')
  lines.push("}")
  lines.push("")
  lines.push("# --- Step 2: ensure the Windows service exists ---------------------------")
  lines.push("$svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue")
  lines.push("if (-not $svc) {")
  lines.push('    Write-SetupLog "MongoDB service \'$ServiceName\' not found. Install MongoDB before running this script." "ERROR"')
  lines.push("    throw \"MongoDB service \'$ServiceName\' not found.\"")
  lines.push("}")
  lines.push('Write-SetupLog "MongoDB service \'$ServiceName\' found. Status: $($svc.Status)"')
  lines.push("")
  lines.push("# --- Step 3: ensure config file exists -----------------------------------")
  lines.push("if (-not (Test-Path $ConfigFile)) {")
  lines.push('    Write-SetupLog "MongoDB config file not found at $ConfigFile. Creating minimal config." "WARN"')
  lines.push("@\"")
  lines.push("systemLog:")
  lines.push("    destination: file")
  lines.push("    path: $LogPath")
  lines.push("    logAppend: true")
  lines.push("storage:")
  lines.push("    dbPath: $DbPath")
  lines.push("net:")
  lines.push("    bindIp: $BindIp")
  lines.push("    port: $Port")
  lines.push("\"@ | Set-Content -Path $ConfigFile -Encoding UTF8")
  lines.push("}")
  lines.push("")
  lines.push("# --- Step 4: idempotently inject replication.replSetName ------------------")
  lines.push("$content = Get-Content $ConfigFile -Raw")
  lines.push('$expectedReplication = "  replication:`n    replSetName: `"$ReplicaSetName`""')
  lines.push("")
  // The regex strings below contain backslashes that JS would otherwise
  // interpret as escape sequences. We hand-roll them with double-backslashes
  // so the final PowerShell output is verbatim.
  // eslint-disable-next-line no-useless-escape
  const matchAlready =
    '"(?ms)^\\s*replication:\\s*\\r?\\n\\s*replSetName:\\s*[`"\'?]?$ReplicaSetName[`"\'?]?"'
  // eslint-disable-next-line no-useless-escape
  const matchAny =
    '"(?ms)^\\s*replication:\\s*\\r?\\n\\s*replSetName:.*?(\\r?\\n)"'
  lines.push("if ($content -match " + matchAlready + ") {")
  lines.push('    Write-SetupLog "replSetName already configured. Skipping edit."')
  lines.push("} else {")
  lines.push("    if ($content -match " + matchAny + ") {")
  lines.push('        Write-SetupLog "Existing replication block found with different name — replacing it." "WARN"')
  lines.push(
    "        $content = $content -replace " + matchAny + ", $expectedReplication",
  )
  lines.push("    } else {")
  lines.push('        $content += "`n`nreplication:`n  replSetName: `"$ReplicaSetName`"`n"')
  lines.push("    }")
  lines.push("    Set-Content -Path $ConfigFile -Value $content -Encoding UTF8")
  lines.push('    Write-SetupLog "Wrote replication.replSetName = $ReplicaSetName to $ConfigFile"')
  lines.push("}")
  lines.push("")
  lines.push("# --- Step 5: restart the service -----------------------------------------")
  lines.push("if ($svc.Status -ne 'Stopped') {")
  lines.push('    Write-SetupLog "Stopping MongoDB service to apply config."')
  lines.push("    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue")
  lines.push("    Start-Sleep -Seconds 5")
  lines.push("}")
  lines.push('Write-SetupLog "Starting MongoDB service."')
  lines.push("Start-Service -Name $ServiceName")
  lines.push("Start-Sleep -Seconds 5")
  lines.push("")
  lines.push("$svc = Get-Service -Name $ServiceName")
  lines.push("if ($svc.Status -ne 'Running') {")
  lines.push('    Write-SetupLog "MongoDB service did not reach Running state. Current: $($svc.Status)" "ERROR"')
  lines.push("    throw \"MongoDB service not running.\"")
  lines.push("}")
  lines.push('Write-SetupLog "MongoDB service is running."')
  lines.push("")
  lines.push("# --- Step 6: connect to mongosh and check replica set status -------------")
  lines.push("$mongosh = Get-Command mongosh.exe -ErrorAction SilentlyContinue")
  lines.push("if (-not $mongosh) {")
  lines.push('    Write-SetupLog "mongosh not on PATH. Install MongoDB Shell or update PATH." "ERROR"')
  lines.push("    throw \"mongosh not found.\"")
  lines.push("}")
  lines.push("")
  lines.push(
    '$statusJson = & $mongosh.Source --quiet --eval "try { rs.status(); } catch (e) { print(\'NOT_INITIALIZED\'); }"',
  )
  lines.push('if ($statusJson -match \'NOT_INITIALIZED\' -or $statusJson -match \'"ok"\\s*:\\s*0\') {')
  lines.push('    Write-SetupLog "Replica set not initialized — initializing now."')
  lines.push(
    "    & $mongosh.Source --quiet --eval \"rs.initiate({ _id: \'$ReplicaSetName\', members: [ { _id: 0, host: \'$BindIp:$Port\' } ] })\"",
  )
  lines.push("    Start-Sleep -Seconds 5")
  lines.push("} else {")
  lines.push('    Write-SetupLog "Replica set already initialized — skipping."')
  lines.push("}")
  lines.push("")
  lines.push('Write-SetupLog "Final replica set status:"')
  lines.push('& $mongosh.Source --quiet --eval "JSON.stringify(rs.status(), null, 2)"')
  lines.push('Write-SetupLog "MongoDB setup complete."')

  return lines.join("\n") + "\n"
}

/** Escape a string for embedding inside a double-quoted PowerShell string. */
function escapePowerShell(input: string): string {
  return input.replace(/`/g, "``").replace(/"/g, '`"').replace(/\$/g, "`$")
}
